# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0b0ddc2fed29cde320ce3084340b358d34e19e90f6bbca7a08f2e66af3e49462d079831a63c1e461153552ba4ea3d4974a28c5badd3aa42753299dc9275d7a8

test:
  secret_key_base: f262c89d9a37a6b446c9e45cccd0a6f11ce04769b0244f7c6f4b254db1aa193da92eb7a3c852ece43d6ca8dcf334b7598043eaaf7669a2a11aad46a498f70ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
